# Generated by Django 4.0.5 on 2022-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itenscompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.IntegerField(choices=[(1, 'Carrinho 3'), (2, 'Realizado'), (3, 'Pago'), (4, 'Entregue')], default=1),
        ),
    ]
